version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

    open-pull-requests-limit: 100

    labels:
      - dependencies

    commit-message:
      prefix: "deps"

    reviewers:
      - syedalinaqihasni
